name: M3U generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use Python 3.11 to avoid build issues

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev python3-dev gcc
      
      - name: Lock pip version
        run: python -m pip install --upgrade pip==23.3.2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install lxml --only-binary :all:
          pip install -r requirements.txt

      - name: Run M3U Generator script
        run: python scripts/generator.py

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.email "visionintegral@gmail.com"
          git config --global user.name "zeknewbe"
          git add -A
          git commit -m "Update M3U Playlist"
          git push --no-verify
