name: M3U generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev python3-dev build-essential
          pip install -r requirements.txt

      - name: Install Python Dependencies
        run: |
          python3.12 -m venv venv
          source venv/bin/activate
          pyenv install 3.12.2
          pyenv global 3.12.2
          pip install -r requirements.txt

      - name: Run Script
        run: python scripts/generator.py

      - name: Check for Changes
        id: git-check
        run: |
          git diff --quiet || echo "changes_exist=true" >> $GITHUB_OUTPUT

      - name: Commit Changes
        if: steps.git-check.outputs.changes_exist == 'true'
        run: |
          git config --global user.email "visionintegral@gmail.com"
          git config --global user.name "zeknewbe"
          git add -A
          git commit -m "Update M3U Playlist"
          git push
